function [Vermelho,Azul,laranja] = Cores(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 05-Dec-2024
%------------------------------------------------------

%% Vermelho
% Convert RGB image to chosen color space
I = RGB;

% Define thresholds for channel 1 based on histogram settings
channel1Min = 157.000;
channel1Max = 255.000;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.000;
channel2Max = 49.000;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 19.000;
channel3Max = 74.000;

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
  (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
  (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
Vermelho = sliderBW;

%% Azul
% Define thresholds for channel 1 based on histogram settings
channel1Min = 0.000;
channel1Max = 37.000;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 53.000;
channel2Max = 98.000;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 126.000;
channel3Max = 185.000;
% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
  (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
  (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
Azul = sliderBW;

%% Laranja
% Define thresholds for channel 1 based on histogram settings
channel1Min = 147.000;
channel1Max = 242.000;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 54.000;
channel2Max = 105.000;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.000;
channel3Max = 29.000;

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
  (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
  (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
laranja = sliderBW;

end
